Repository 2025-II-PFC-FLP/taller-2-pfc-2025-ii-ssssn, pull requests merged in 2025-10, with the labels that each got.

#5 Realización función igualdad y test complementos
  app/src/main/scala/taller/ConjuntosDifusos.scala
  app/src/test/scala/taller/ConjuntosDifusosTest.scala
Labels: enhancement

#6 Se comienza a realizar la documentación y la modificación del Readme.
  README.md
  docs/InformeDesarrollo.md
Labels: documentation

#9 se resuelven algunos problemas con los tests
  app/src/test/scala/taller/ConjuntosDifusosTest.scala
Labels: bug, enhancement

#13 Se agregan más ejemplos de llamado de pila.
  docs/InformeDesarrollo.md
Labels: documentation
